- update ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,25 +4,80 @@ on:
   push:
   workflow_dispatch:
   schedule:
-    - cron: "0 4 * * *"
+    - cron: "0 3 * * *"
 
 jobs:
   build: 
     runs-on: ubuntu-latest
 
     steps:
+      - name: Get current date
+        id: date
+        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
+
       - uses: actions/checkout@v3
+
       - name: Set up Python 3.8
         uses: actions/setup-python@v4
         with:
           python-version: 3.8
+
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install requests lxml
-      - name: Run Python
+
+      - name: Run python to generate ASN and IP list
+        id: generate
         run: |
-          python scripts/ChinaASN.py
-      - uses: stefanzweifel/git-auto-commit-action@v4
+          python main.py
+
+      - name: Check generate result
+        run: |
+            if [[ "${{ steps.generate.outputs.generate_result }}" == "success" ]];
+            then
+              echo "Data Generate Success, start release process."
+            else 
+              echo "Data Generate Failed, please check the log."
+              exit 1
+            fi
+
+      - name: Create release
+        id: create_release
+        uses: actions/create-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
-          commit_message: Update ASN&IP List
+          tag_name: ${{ steps.date.outputs.date }}
+          release_name: ASN-IP-Data-${{ steps.date.outputs.date }}
+          body: |
+            [${{ steps.date.outputs.date }}] auto generated ASN and IP list result.
+          draft: true
+          prerelease: false
+
+      - name: Upload release asset
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: ${{ steps.generate.outputs.release_file_path}}
+          asset_name: ${{ steps.generate.outputs.release_file}}
+          asset_content_type: ${{ steps.generate.outputs.release_file_content_type}}
+
+      - name: Publish release
+        uses: StuYarrow/publish-release@v1.1.2
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          id: ${{ steps.create_release.outputs.id }}
+
+      - name: Delete old releases and workflows
+        uses: ophub/delete-releases-workflows@main
+        with:
+          delete_releases: true
+          releases_keep_latest: 5
+          delete_tags: true
+          delete_workflows: true
+          workflows_keep_day: 10
+          gh_token: ${{ secrets.GITHUB_TOKEN }}
